"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-21

Hand-written rather than autogenerated, since it's the first migration and there's
no prior DB state to diff against. Every migration after this one should come from
`alembic revision --autogenerate` and be reviewed, not hand-written.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "sites",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("principal_investigator_name", sa.String(255), nullable=False),
        sa.Column("contact_email", sa.String(320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "protocols",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("site_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sites.id"), nullable=False),
        sa.Column("sponsor_name", sa.String(255), nullable=False),
        sa.Column("protocol_number", sa.String(100), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("irb_approval_expiry_override", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_protocols_site_id", "protocols", ["site_id"])

    document_status = postgresql.ENUM(
        "pending_extraction",
        "pending_human_review",
        "accepted",
        "rejected",
        "superseded",
        name="document_status",
    )
    document_status.create(op.get_bind())

    op.create_table(
        "binder_documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("protocol_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("protocols.id"), nullable=False),
        sa.Column("document_type_id", sa.String(100), nullable=False),
        sa.Column("original_filename", sa.String(500), nullable=False),
        sa.Column("blob_path", sa.String(1000), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="document_status", create_type=False),
            nullable=False,
            server_default="pending_extraction",
        ),
        sa.Column("classification_confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("extracted_effective_date", sa.Date(), nullable=True),
        sa.Column("extracted_expiry_date", sa.Date(), nullable=True),
        sa.Column("extracted_signer_name", sa.String(255), nullable=True),
        sa.Column("extracted_signed_date", sa.Date(), nullable=True),
        sa.Column("version_label", sa.String(50), nullable=True),
        sa.Column("superseded_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("binder_documents.id"), nullable=True),
        sa.Column("uploaded_by", sa.String(255), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_binder_documents_protocol_id", "binder_documents", ["protocol_id"])
    op.create_index(
        "ix_binder_documents_protocol_type", "binder_documents", ["protocol_id", "document_type_id"]
    )

    op.create_table(
        "gap_check_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("protocol_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("protocols.id"), nullable=False),
        sa.Column("triggered_by", sa.String(255), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("report_json", postgresql.JSONB(), nullable=False),
    )
    op.create_index("ix_gap_check_runs_protocol_id", "gap_check_runs", ["protocol_id"])

    op.create_table(
        "audit_log_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("actor", sa.String(255), nullable=False),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(100), nullable=False),
        sa.Column("entity_id", sa.String(100), nullable=False),
        sa.Column("details_json", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("request_id", sa.String(100), nullable=True),
    )
    op.create_index("ix_audit_log_entries_entity", "audit_log_entries", ["entity_type", "entity_id"])


def downgrade() -> None:
    op.drop_table("audit_log_entries")
    op.drop_table("gap_check_runs")
    op.drop_index("ix_binder_documents_protocol_type", table_name="binder_documents")
    op.drop_index("ix_binder_documents_protocol_id", table_name="binder_documents")
    op.drop_table("binder_documents")
    postgresql.ENUM(name="document_status").drop(op.get_bind())
    op.drop_index("ix_protocols_site_id", table_name="protocols")
    op.drop_table("protocols")
    op.drop_table("sites")
